name: 'Node Dependency'
description: 'Automatically generates node dependency reports by provided parameters'
author: 'AlexRogalskiy'

inputs:
  mode:
    description: 'Operation mode (package_versions / multi_package_versions)'
    required: true
  reportFile:
    description: 'Target report file name'
    required: false
  reportPath:
    description: 'Target report file path'
    required: false

outputs:
  reportStatus:
    description: 'Report representation status'

runs:
  using: 'docker'
  image: 'Dockerfile'

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'file'
  color: 'orange'
