name: label-sponsor

on:
  issues:
    types:
      - 'opened'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set sponsor label
        uses: JasonEtco/is-sponsor-label-action@e54ba6b74c9297a11dd65e2dd8b711de8648e76c
        with:
          label: ":sparkling_heart: sponsor"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
